# Use the official nginx image as the base image
FROM nginx

# Copy the default.conf file to the nginx conf.d directory
# This copies the default.conf file, which contains the nginx configuration, to the /etc/nginx/conf.d/ directory in the container.
COPY ./default.conf /etc/nginx/conf.d/default.conf